# _config.yml
title: "Learn HPC Lessons"
description: "A collection of text-based lessons on high-performance computing."
baseurl: "" # Leave empty for project page if repo name is learn-hpc, otherwise use /repo-name if it is different.
theme: minimal
