title: Learn HPC Lessons  # Your site title
description: Lessons in High-Performance Computing # Your site description
theme: jekyll-theme-minimal # Use a simple theme
baseurl: "/learn_hpc" # IMPORTANT: Set to your repo name, e.g., "/learn_hpc"
