title: "Learn HPC Lessons"
description: "A collection of text-based lessons on high-performance computing."
baseurl: "/learn_hpc"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
